---
title: "家庭動態社會調查主樣本的生活滿意度分數（依性別、出生世代、年齡組）"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
---

```{r}
load("cohortmf.Rda")
load("plotmf_cohort.Rda")
```

  Happy 
=======================================

Column 
-------------------------------------

### Male
    
```{r}
graph9$happym
```

Column
-------------------------------------

### Female

```{r}
graph9$happyf
```

  Life
=======================================

Column
---------------------------------------

### Male

```{r}
graph9$lifem
```

Column
---------------------------------------

### Female

```{r}
graph9$lifef
```

  Health
=======================================

Column
----------------------------------------

### Male

```{r}
graph9$healthm
```

Column
----------------------------------------

### Female

```{r}
graph9$healthf
```

  Shealth
========================================

Column
----------------------------------------

### Male

```{r}
graph9$Shealthm
```

Column
----------------------------------------

### Female

```{r}
graph9$Shealthf
```

  Eco_satisfaction
=========================================
Column
----------------------------------------

### Male

```{r}
graph9$eco_satism
```

Column
----------------------------------------

### Female

```{r}
graph9$eco_satisf
```

  Work_satisfaction
===========================================
Column
----------------------------------------

### Male

```{r}
graph9$work_satism
```

Column
----------------------------------------

### Female

```{r}
graph9$work_satisf
```

  Family_satisfaction
==========================================
Column
------------------------------------------

### Male

```{r}
graph9$family_satism
```

Column
------------------------------------------

### Female

```{r}
graph9$family_satisf
```

  Marry_satisfaction
==========================================
Column
------------------------------------------

### Male

```{r}
graph9$marry_satism
```

Column
-----------------------------------------

### Female

```{r}
graph9$marry_satisf
```
