---
title: "家庭動態社會調查主樣本的生活滿意度分數（出生世代）"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
---

```{r}
load("cohort.Rda")
load("plot_cohort.Rda")
load("cohort2.Rda")
load("plot2_cohort.Rda")
```

  Happy 
=======================================

Column 
-------------------------------------

### Happiness Grand mean
    
```{r}
graph5$happy
```

Column
-------------------------------------

### Happiness Group mean

```{r}
graph6$happy
```

  Life
=======================================

Column
---------------------------------------

### Life Grand mean

```{r}
graph5$life
```

Column
---------------------------------------

### Life Group mean

```{r}
graph6$life
```

  Health
=======================================

Column
----------------------------------------

### Health Grand mean

```{r}
graph5$health
```

Column
----------------------------------------

### Health Group mean

```{r}
graph6$health
```

  Shealth
========================================

Column
----------------------------------------

### Shealth Grand mean

```{r}
graph5$Shealth
```

Column
----------------------------------------

### Shealth Group mean

```{r}
graph6$Shealth
```

  Eco_satisfaction
=========================================
Column
----------------------------------------

### Eco_satis Grand mean

```{r}
graph5$eco_satis
```

Column
----------------------------------------

### Eco_satis Group mean

```{r}
graph6$eco_satis
```

  Work_satisfaction
===========================================
Column
----------------------------------------

### Work_satis Grand mean

```{r}
graph5$work_satis
```

Column
----------------------------------------

### Work_satis Group mean

```{r}
graph6$work_satis
```

  Family_satisfaction
==========================================
Column
------------------------------------------

### Family_satis Grand mean

```{r}
graph5$family_satis
```

Column
------------------------------------------

### Family_satis Group mean

```{r}
graph6$family_satis
```

  Marry_satisfaction
==========================================
Column
------------------------------------------

### Marry_satis Grand mean

```{r}
graph5$marry_satis
```

Column
-----------------------------------------

### Marry_satis Group mean

```{r}
graph6$marry_satis
```






