---
title: "家庭動態社會調查主樣本的生活滿意度"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
---
```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
```

```{r}
load("psfdPlot.Rda")
```

生活快樂與順遂分數
=======================================================================

column
-------------------------------------
### 主樣本波次(1~5)

```{r}
graph$happylife
```   

column
---------------------------------------- 
### 1930~2000(每十年一波次)
    
```{r}
graph$happylife_10
```

自己與其伴侶的健康分數
=======================================================================

column
-------------------------------------
### 主樣本波次(1~5)

```{r}
graph$health
```  

column
-------------------------------------
### 1930~2000(每十年一波次)
```{r}
graph$health_10
```

工作、經濟滿意度分數
=======================================================================

column
---------------------------------------- 
### 主樣本波次(1~5)

```{r}
graph$work
```

column
---------------------------------------- 
### 1930~2000(每十年一波次)
```{r}
graph$work_10
```

家庭、婚姻(同居)滿意度分數
=======================================================================

column
---------------------------------------- 
### 主樣本波次(1~5)
```{r}
graph$family
```

column
---------------------------------------- 
### 1930~2000(每十年一波次)
```{r}
graph$family_10
```

