---
title: "psfd"
author: "Wang"
date: "2020/9/25"
output: html_document
---

library(foreign)
library(ggplot2)
library(dplyr)
library(extrafont)
library(colorspace) 
library(ggpubr)
loadfonts("win")
library("rio")
library('dplyr')
library("tidyverse")

```{r}
import("D:/satis/RIRRR.sav")->Kuo
Kuo %>%
  group_by(id) %>%
  fill(scale, .direction = "downup") %>%
  ungroup()->wang
wang %>%
  group_by(id) %>%
  mutate(birth_y2 = first(na.omit(birth_y)))->wang
```

### happy life
wang %>%
  drop_na(happy) %>% 
  group_by(scale) %>%
  summarise(point=mean(happy),n=n())->d1
wang %>%
  drop_na(life) %>% 
  group_by(scale) %>%
  summarise(point=mean(life),n=n())->d2
d1$point <- round(d1$point, digits=2)
d2$point <- round(d2$point, digits=2)
d1 <- data.frame(d1,category=c("H","H","H","H","H"))
d2 <- data.frame(d2,category=c("L","L","L","L","L"))
d3 <- rbind(d1,d2)
labelsx <- c("1953-64","1935-54","1964-76","1977-83","1984-91")

###health Shealth
wang %>%
  drop_na(health) %>% 
  group_by(scale) %>%
  summarise(point=mean(health),n=n())->d4
wang %>%
  drop_na(Shealth) %>% 
  group_by(scale) %>%
  summarise(point=mean(Shealth),n=n())->d5
d4$point <- round(d4$point, digits=2)
d5$point <- round(d5$point, digits=2)
d4 <- data.frame(d4,category=c("O","O","O","O","O"))
d5 <- data.frame(d5,category=c("S","S","S","S","S"))
d6 <- rbind(d4,d5)

### work family eco marry satis
wang %>%
  drop_na(work_satis) %>% 
  group_by(scale) %>%
  summarise(point=mean(work_satis),n=n())->d7
wang %>%
  drop_na(family_satis) %>% 
  group_by(scale) %>%
  summarise(point=mean(family_satis),n=n())->d8
wang %>%
  drop_na(eco_satis) %>% 
  group_by(scale) %>%
  summarise(point=mean(eco_satis),n=n())->d9
wang %>%
  drop_na(marry_satis) %>% 
  group_by(scale) %>%
  summarise(point=mean(marry_satis),n=n())->d10
d7$point <- round(d7$point, digits=2)
d8$point <- round(d8$point, digits=2)
d7 <- data.frame(d7,category=c("W","W","W","W","W"))
d8 <- data.frame(d8,category=c("F","F","F","F","F"))
d9$point <- round(d9$point, digits=2)
d10$point <- round(d10$point, digits=2)
d9 <- data.frame(d9,category=c("E","E","E","E","E"))
d10 <- data.frame(d10,category=c("M","M","M","M","M"))
d11 <- rbind(d7,d9)
d12 <- rbind(d8,d10)

###save data
save(
  d3,d6,d11,d12,labelsx,
  data3,data6,data11,data12,labelsx2,mytheme,
  file="psfddata.Rda")

### 作圖 d3 ylim(4.65,5.2)
graph<-list()
d3 %>%
  ggplot(aes(x=scale, y=point, group=category, color=category))+
  geom_line(linetype="solid", size=1,alpha=0.4)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=point,size=5,
    vjust=1.5,hjust=0,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx)+
  scale_color_discrete(
  labels=c("Happy","Life"))+
  labs(
    title="主樣本的生活快樂感和生活過得好不好",
    x="主樣本波次",y="平均分數",
    caption = "(4 ~ 5.5區間，1分最低，7分最高)")+
    mytheme+ylim(4,5.5)+
    annotate("text",x = 1:5, y=5.5,size=4, label=c("4981","9714","5834","9504","3554"),colour="#F8766D",fontface="bold")+
annotate("text",x = 1:5, y=5.4,size=4, label=c("4980","9718","5835","9504","3558"),colour="#00BFC4",fontface="bold")+
annotate("text",x=0.6,y=5.45,size=5,label="N",fontface="bold")->graph$happylife
###d6 
d6 %>%
  ggplot(aes(x=scale, y=point, group=category, color=category))+
  geom_line(linetype="solid", size=1,alpha=0.4)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=point,size=5,
    vjust=1.2,hjust=1.2,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx)+
  scale_color_discrete(
  labels=c("Health","Shealth"))+
  labs(
    title="主樣本和其伴侶的自評健康分數",x="主樣本波次",y="平均分數",caption = "(2.5 ~ 4.5區間，1分最低，5分最高)")+
    mytheme+ylim(2.5,4.5)+
    annotate("text",x = 1:5, y=4.5,size=4, label=c("5977","11683","6983","11687","3559"),colour="#F8766D",fontface="bold")+
annotate("text",x = 1:5, y=4.4,size=4, label=c("4871","8745","5136","5439","1147"),colour="#00BFC4",fontface="bold")+
annotate("text",x=0.5,y=4.45,size=5,label="N",fontface="bold")->graph$health
###d11
d11 %>%
  ggplot(aes(x=scale, y=point, group=category, color=category))+
  geom_line(linetype="solid", size=1,alpha=0.4)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=point,size=5,
    vjust=1.6,hjust=1,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx)+
  scale_color_discrete(
  labels=c("Eco","Work"))+
  labs(
  title=
    "主樣本的工作、經濟滿意度分數",
      x="主樣本波次",y="平均分數",
        caption="(2.5 ~ 3.5區間，1分最低，4分最高)")+
        mytheme+ylim(2.5,3.5)+
        annotate("text",x = 1:5, y=3.5,size=4, label=c("3492","3143","5091","8402","1419"),colour="#00BFC4",fontface="bold")+
annotate("text",x = 1:5, y=3.4,size=4, label=c("956","1707","1094","2914","1582"),colour="#F8766D",fontface="bold")+
annotate("text",x=0.5,y=3.45,size=5,label="N",fontface="bold")->graph$work
###d12
d12 %>%
  ggplot(aes(x=scale, y=point, group=category, color=category))+
  geom_line(linetype="solid", size=1,alpha=0.4)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=point,size=5,
    vjust=1.6,hjust=0.8,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx)+
  scale_color_discrete(
  labels=c("Family","Marry"))+
  theme_light()+
  theme(text=element_text(size=10, family="Comic Sans MS"),
  axis.text.x=element_text(angle=45,vjust=0.5))+
  labs(
  title=
    "主樣本的家庭、婚姻(同居)滿意度分數",
      x="主樣本波次",y="平均分數",
        caption="(2.5 ~ 3.5區間，1分最低，4分最高)")+
        mytheme+ylim(2.5,3.5)+annotate("text",x = 1:5, y=3.5,size=4, label=c("365","536","418","954","570"),colour="#00BFC4",fontface="bold")+
annotate("text",x = 1:5, y=3.4,size=4, label=c("4978","9699","5831","9501","1584"),colour="#F8766D",fontface="bold")+
annotate("text",x=0.5,y=3.45,size=5,label="N",fontface="bold")->graph$family
save(graph, file="psfdPlot.Rda")

### happy life n
d3 %>%
  filter(category == "H") %>%
  ggplot(aes(x=scale,y=n))+
  geom_bar(stat="identity", fill="#F8766D", width=0.7)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=n,size=5,
    vjust=1.5,hjust=0,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx)+
  labs(
    title="生活快樂感(N)",x="波次",y="平均分數",caption = "(1分最低，7分最高)")+mytheme->graph$happyn

d3 %>%
  filter(category == "L") %>%
  ggplot(aes(x=scale,y=n))+
  geom_bar(stat="identity", fill="#00BFC4", width=0.7)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=n,size=5,
    vjust=1.5,hjust=0,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx)+
  labs(
    title="生活過得好不好(N)",x="波次",y="平均分數",caption = "(1分最低，7分最高)")+mytheme->graph$lifen
    
### health Shealth n
d6 %>%
  filter(category == "O") %>%
  ggplot(aes(x=scale,y=n))+
  geom_bar(stat="identity", fill="#F8766D", width=0.7)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=n,size=5,
    vjust=1.5,hjust=0,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx)+
  labs(
    title="自評健康分數(N)",x="波次",y="平均分數",caption = "(1分最低，5分最高)")+mytheme->graph$healthn

d6 %>%
  filter(category == "S") %>%
  ggplot(aes(x=scale,y=n))+
  geom_bar(stat="identity", fill="#00BFC4", width=0.7)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=n,size=5,
    vjust=1.5,hjust=0,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx)+
  labs(
    title="伴侶健康分數(N)",x="波次",y="平均分數",caption = "(1分最低，5分最高)")+mytheme->graph$Shealthn
    
### eco work
d11 %>%
  filter(category == "E") %>%
  ggplot(aes(x=scale,y=n))+
  geom_bar(stat="identity", fill="#F8766D", width=0.7)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=n,size=5,
    vjust=1.5,hjust=0,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx)+
  labs(
    title="經濟滿意度(N)",x="波次",y="平均分數",caption = "(1分最低，4分最高)")+mytheme->graph$econ
    
d11 %>%
  filter(category == "W") %>%
  ggplot(aes(x=scale,y=n))+
  geom_bar(stat="identity", fill="#00BFC4", width=0.7)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=n,size=5,
    vjust=1.5,hjust=0,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx)+
  labs(
    title="工作滿意度(N)",x="波次",y="平均分數",caption = "(1分最低，4分最高)")+mytheme->graph$workn
    
### family marry
d12 %>%
  filter(category == "F") %>%
  ggplot(aes(x=scale,y=n))+
  geom_bar(stat="identity", fill="#F8766D", width=0.7)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=n,size=5,
    vjust=1.5,hjust=0,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx)+
  labs(
    title="家庭滿意度(N)",x="波次",y="平均分數",caption = "(1分最低，4分最高)")+mytheme->graph$familyn

d12 %>%
  filter(category == "M") %>%
  ggplot(aes(x=scale,y=n))+
  geom_bar(stat="identity", fill="#00BFC4", width=0.7)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=n,size=5,
    vjust=1.5,hjust=0,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx)+
  labs(
    title="婚姻(同居)滿意度(N)",x="波次",y="平均分數",caption = "(1分最低，4分最高)")+mytheme->graph$marryn

ggarrange(graph$happylife,
  ggarrange(graph$happyn,graph$lifen,nrow=2),
  widths = c(7,3),ncol=2 )->graph$happylifen

ggarrange(graph$health,
  ggarrange(graph$healthn,graph$Shealthn,nrow=2),
  widths = c(7,3),ncol=2)->graph$happylifen
