---
title: "psfd3"
author: "Wang"
date: "2020/10/8"
output: html_document
---
library(foreign)
library(ggplot2)
library(dplyr)
library(extrafont)
library(tidyverse)
library(colorspace) 
library(shinyjs)
library(plotly)
library(stringr)
loadfonts("win")

### raw data
wang <- read.spss("D:/satis/RIRR_1.sav", to.data.frame = TRUE)

mydata = wang[c("scale","period","happy","life","health","Shealth","eco_satis","work_satis","family_satis", "marry_satis")]

scale <- c("1953-64主樣本","1935-54主樣本",
  "1964-76主樣本","1977-83主樣本","1984-91主樣本")
  
  
### choose colour
choose_palette(gui="shiny")    
colorspace::sequential_hcl(n = 5, h = c(8, 310), c = c(80, NA, 40), l = c(40, 75), power = c(1, 1), register = "Custom-Palette")->pal

### happy clean data
mydata %>%
  drop_na(happy) %>%
  group_by(scale, period) %>%
  mutate(point=mean(happy),n=n())->happy
happy$point <- round(happy$point, digits=2)

### life clean data
mydata %>%
  drop_na(life) %>%
  group_by(scale, period) %>%
  mutate(point=mean(life),n=n())->life
life$point <- round(life$point, digits=2)

### health clean data
mydata %>%
  drop_na(health) %>%
  group_by(scale, period) %>%
  mutate(point=mean(health),n=n())->health
health$point <- round(health$point, digits=2)

### Shealth clean data
mydata %>%
  drop_na(Shealth) %>%
  group_by(scale, period) %>%
  mutate(point=mean(Shealth),n=n())->Shealth
Shealth$point <- round(Shealth$point, digits=2)

### eco_satis clean data
mydata %>%
  drop_na(eco_satis) %>%
  group_by(scale, period) %>%
  mutate(point=mean(eco_satis),n=n())->eco_satis
eco_satis$point <- round(eco_satis$point, digits=2)

### work_satis clean data
mydata %>%
  drop_na(work_satis) %>%
  group_by(scale, period) %>%
  mutate(point=mean(work_satis),n=n())->work_satis
work_satis$point <- round(work_satis$point, digits=2)

### family_satis clean data
mydata %>%
  drop_na(family_satis) %>%
  group_by(scale, period) %>%
  mutate(point=mean(family_satis),n=n())->family_satis
family_satis$point <- round(family_satis$point, digits=2)

### marry_satis clean data
mydata %>%
  drop_na(marry_satis) %>%
  group_by(scale, period) %>%
  mutate(point=mean(marry_satis),n=n())->marry_satis
marry_satis$point <- round(marry_satis$point, digits=2)

graph1<-list()
graph2<-list()
graph3<-list()
graph4<-list()


###happy graph

```{r}

tg <- ddply(ToothGrowth, c("supp", "dose"), summarise, length=mean(len))

fig<-list()
happy %>%
  plot_ly(
    x= ~period)->fig
fig %>%
  filter(scale=="1 1953-64年出生之主樣本") %>% add_lines(y=~point, name = "第一波", line=list(shape = "linear"))->fig

fig %>%
  filter(scale=="2 1935-54年出生之主樣本") %>% add_lines(y=~point, name = "第二波", line=list(shape = "linear"))->fig

fig %>%
  filter(scale=="3 1964-76年出生之主樣本") %>% add_lines(y=~point, name = "第三波", line=list(shape = "linear"))->fig

fig %>%
  filter(scale=="4 1977-83年出生之主樣本") %>% add_lines(y=~point, name = "第四波", line=list(shape = "linear"))->fig

fig %>%
  filter(scale=="5 1984-91年出生之主樣本") %>% add_lines(y=~point, name = "第五波", line=list(shape = "linear"))->fig

fig

    y=~point,
    type = 'scatter',
    transforms = list(
      list(
        type = 'groupby',
        groups = ~scale,
        styles = list(
          list(target=1, value = list(marker = list())),
          list(target=2, value = list(marker = list())),
          list(target=3, value = list(marker = list())),
          list(target=4, value = list(marker = list())),
          list(target=5, value = list(marker = list()))))))
          
          
happy %>%
    plot_ly(x=~period, y=~point, color=~scale, colors=pal, type="bar"), text= ~paste(
  "Scale:", ~scale)), 
  "<br>N:", ~n, 
  "<br>Point:", ~point))
```


happy %>%
  ggplot(aes(x=period, y=point, group=scale, color=scale, text = paste(
  "Scale:", strtrim(scale,9), 
  "<br>N:", n, 
  "<br>Point:", point)))+
  geom_line(linetype="solid",alpha=0.4, size=1)+
  geom_point(size=3,alpha=0.8)+
    ggtitle(paste("五波主樣本的生活快樂感"))+
    ylim(4,5.5)->graph1$happyp
ggplotly(
  graph1$happyp, tooltip = "text")->graph1$happyp2

###life graph
life %>%
  ggplot(aes(x=period, y=point, group=scale, color=scale, text = paste(
  "Scale:", strtrim(scale,9), 
  "<br>N:", n, 
  "<br>Point:", point)))+
  geom_line(linetype="solid",alpha=0.4, size=1)+
  geom_point(size=3,alpha=0.8)+
    ggtitle(paste("五波主樣本的生活過得好不好"))+
    ylim(4,5.5)->graph1$lifep
ggplotly(
  graph1$lifep, tooltip = "text")->graph1$lifep2

### health graph
health %>%
  ggplot(aes(x=period, y=point, group=scale, color=scale, text = paste(
  "Scale:", strtrim(scale,9), 
  "<br>N:", n, 
  "<br>Point:", point)))+
  geom_line(linetype="solid",alpha=0.4, size=1)+
  geom_point(size=3,alpha=0.8)+
    ggtitle(paste("五波主樣本的自評健康狀態"))+
    ylim(2.5,4.5)->graph2$healthp
ggplotly(
  graph2$healthp, tooltip = "text")->graph2$healthp2

### Shealth graph
Shealth %>%
  ggplot(aes(x=period, y=point, group=scale, color=scale, text = paste(
  "Scale:", strtrim(scale,9), 
  "<br>N:", n, 
  "<br>Point:", point)))+
  geom_line(linetype="solid",alpha=0.4, size=1)+
  geom_point(size=3,alpha=0.8)+
    ggtitle(paste("五波主樣本的伴侶健康狀態"))+
    ylim(2.5,4.5)->graph2$Shealthp
ggplotly(
  graph2$Shealthp, tooltip = "text")->graph2$Shealthp2
  
### eco_satis graph
eco_satis %>%
  ggplot(aes(x=period, y=point, group=scale, color=scale, text = paste(
  "Scale:", strtrim(scale,9), 
  "<br>N:", n, 
  "<br>Point:", point)))+
  geom_line(linetype="solid",alpha=0.4, size=1)+
  geom_point(size=3,alpha=0.8)+
    ggtitle(paste("五波主樣本的經濟滿意度"))+
    ylim(2.5,3.5)->graph3$eco_satis
ggplotly(
  graph3$eco_satis, tooltip = "text")->graph3$eco_satis2

### work_satis graph
work_satis %>%
  ggplot(aes(x=period, y=point, group=scale, color=scale, text = paste(
  "Scale:", strtrim(scale,9), 
  "<br>N:", n, 
  "<br>Point:", point)))+
  geom_line(linetype="solid",alpha=0.4, size=1)+
  geom_point(size=3,alpha=0.8)+
    ggtitle(paste("五波主樣本的工作滿意度"))+
    ylim(2.5,3.5)->graph3$work_satis
ggplotly(
  graph3$work_satis, tooltip = "text")->graph3$work_satis2
 
### family_satis graph
family_satis %>%
  ggplot(aes(x=period, y=point, group=scale, color=scale, text = paste(
  "Scale:", strtrim(scale,9), 
  "<br>N:", n, 
  "<br>Point:", point)))+
  geom_line(linetype="solid",alpha=0.4, size=1)+
  geom_point(size=3,alpha=0.8)+
    ggtitle(paste("五波主樣本的家庭滿意度"))+
    ylim(2.5,3.5)->graph4$family_satis
ggplotly(
  graph4$family_satis, tooltip = "text")->graph4$family_satis2

### marry_satis graph
marry_satis %>%
  ggplot(aes(x=period, y=point, group=scale, color=scale, text = paste(
  "Scale:", strtrim(scale,9), 
  "<br>N:", n, 
  "<br>Point:", point)))+
  geom_line(linetype="solid",alpha=0.4, size=1)+
  geom_point(size=3,alpha=0.8)+
    ggtitle(paste("五波主樣本的婚姻(同居)滿意度"))+
    ylim(2.5,3.5)->graph4$marry_satis
ggplotly(
  graph4$marry_satis, tooltip = "text")->graph4$marry_satis2


### save data and graph
save(
  happy,life,
  file="psfddata1.Rda")

save(
  health,Shealth,
  file="psfddata2.Rda")
  
save(
  eco_satis,work_satis,
  file="psfddata3.Rda")
  
save(
  family_satis,marry_satis,
  file="psfddata4.Rda")

save(graph1, file="psfdPlot1.Rda")
save(graph2, file="psfdPlot2.Rda")
save(graph3, file="psfdPlot3.Rda")
save(graph4, file="psfdPlot4.Rda")