---
title: "psfd2"
author: "Wang"
date: "2020/9/26"
output: html_document
---

library(foreign)
library(ggplot2)
library(extrafont)
library(dplyr)
loadfonts("win")

wang <- read.spss("D:/satis/RIRR_1.sav", to.data.frame = TRUE)

=======
wang <- read.spss("C:/Users/steve/Downloads/satis/RIRR_1.sav", to.data.frame = TRUE)

###summary(wang$birth_y)
wang$birth<-as.numeric(
  levels(wang$birth_y)[wang$birth_y])
###summary(wang$birth)
for(i in 1:nrow(wang)){
  if(wang$birth[i] %in% 23:28){
    wang$birth_p[i]<-"1"
  }else if (wang$birth[i] %in% 29:38){wang$birth_p[i]<-"2"
  }else if (wang$birth[i] %in% 39:48){wang$birth_p[i]<-"3"
  }else if (wang$birth[i] %in% 49:58){wang$birth_p[i]<-"4"
  }else if (wang$birth[i] %in% 59:68){wang$birth_p[i]<-"5"
  }else if (wang$birth[i] %in% 69:78){wang$birth_p[i]<-"6"
  }else if (wang$birth[i] %in% 79:88){wang$birth_p[i]<-"7"
  }else{wang$birth_p[i]<-NA
  }
}
###summary(wang$birth_p)    table(wang$birth_p, wang$birth)

labelsx2 <- c("1934-39","1940-49","1950-59","1960-69","1970-79","1980-89","1990-91")
### happy life
wang %>%
  drop_na(happy) %>% 
  drop_na(birth_p) %>%
  group_by(birth_p) %>%
  summarise(point=mean(happy),n=n())->data1
wang %>%
  drop_na(life) %>% 
  drop_na(birth_p) %>%
  group_by(birth_p) %>%
  summarise(point=mean(life),n=n())->data2
data1$point <- round(data1$point, digits=2)
data2$point <- round(data2$point, digits=2)
data1 <- data.frame(data1,category=c("H","H","H","H","H","H","H"))
data2 <- data.frame(data2,category=c("L","L","L","L","L","L","L"))
data3 <- rbind(data1,data2)

### health Shealth
wang %>%
  drop_na(health) %>% 
  drop_na(birth_p) %>%
  group_by(birth_p) %>%
  summarise(point=mean(health),n=n())->data4
wang %>%
  drop_na(Shealth) %>% 
  drop_na(birth_p) %>%
  group_by(birth_p) %>%
  summarise(point=mean(Shealth),n=n())->data5
data4$point <- round(data4$point, digits=2)
data5$point <- round(data5$point, digits=2)
data4 <- data.frame(data4,category=c("O","O","O","O","O","O","O"))
data5 <- data.frame(data5,category=c("S","S","S","S","S","S","S"))
data6 <- rbind(data4,data5)
### work eco family marry
wang %>%
  drop_na(work_satis) %>% 
  drop_na(birth_p) %>%
  group_by(birth_p) %>%
  summarise(point=mean(work_satis),n=n())->data8
wang %>%
  drop_na(eco_satis) %>% 
  drop_na(birth_p) %>%
  group_by(birth_p) %>%
  summarise(point=mean(eco_satis),n=n())->data7
data7$point <- round(data7$point, digits=2)
data8$point <- round(data8$point, digits=2)
data7 <- data.frame(data7,category=c("E","E","E","E","E","E","E"))
data8 <- data.frame(data8,category=c("W","W","W","W","W","W","W"))
data11 <- rbind(data7,data8)

wang %>%
  drop_na(family_satis) %>% 
  drop_na(birth_p) %>%
  group_by(birth_p) %>%
  summarise(point=mean(family_satis),n=n())->data9
wang %>%
  drop_na(marry_satis) %>% 
  drop_na(birth_p) %>%
  group_by(birth_p) %>%
  summarise(point=mean(marry_satis),n=n())->data10
data9$point <- round(data9$point, digits=2)
data10$point <- round(data10$point, digits=2)
data9 <- data.frame(data9,category=c("F","F","F","F","F","F","F"))
data10 <- data.frame(data10,category=c("M","M","M","M","M","M","M"))
data12 <- rbind(data9,data10)
###my theme
mytheme<-theme_light()+
  theme(
    plot.title=element_text(size=20,color="brown", family="Calibri",hjust=0.5),
    plot.caption=element_text(size=15,family="Arial Black"),
    axis.text=element_text(size=15,family="Arial Black"),
    axis.title=element_text(size=18,family="serif"),
    axis.text.x=element_text(angle=45,size=12,vjust=0.5),
    legend.text=element_text(size=12,family="Arial Black"),
    legend.title=element_text(size=12,family="Arial Black"),
    legend.position = "top",
    legend.background = element_rect(fill="lightblue", 
                                  size=0.5, linetype="solid"))

graph<-list()
### graph$happylife_10
data3 %>%
  ggplot(aes(x=birth_p, y=point, group=category, color=category))+
  geom_line(linetype="solid",alpha=0.4, size=1)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=point,size=5,
    vjust=1.5,hjust=0,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx2)+
  scale_color_discrete(
  labels=c("Happy","Life"))+
  labs(
    title="主樣本的生活快樂感和生活過得好不好",
    x="主樣本出生年度(每十年一單位)",y="平均分數",
    caption = "(4 ~ 5.5區間，1分最低，7分最高)")+
  mytheme+ylim(4,5.5)+
  annotate("text",x = 1:7, y=5.5,size=4, label=c("2133","4673","6001","4484","7112","8236","945"),colour="#F8766D",fontface="bold")+
annotate("text",x = 1:7, y=5.4,size=4, label=c("2137","4672","6001","4483","7114","8236","948"),colour="#00BFC4",fontface="bold")+
annotate("text",x=0.5,y=5.45,size=5,label="N",fontface="bold")+labs(title="主樣本的生活快樂感和生活過得好不好",x="主樣本出生世代",y="平均分數",caption = "(1分最低，7分最高)")->graph$happylife10
###happy life n
data3 %>%
  filter(category == "H") %>%
  ggplot(aes(x=birth_p,y=n))+
  geom_bar(stat="identity", fill="#F8766D", width=0.7)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=n,size=5,
    vjust=1.5,hjust=0,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx2)+
  labs(
    title="生活快樂感(N)",x="年度",y="平均分數",caption = "(1分最低，7分最高)")+mytheme->graph$happy10n

data3 %>%
  filter(category == "L") %>%
  ggplot(aes(x=birth_p,y=n))+
  geom_bar(stat="identity", fill="#00BFC4", width=0.7)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=n,size=5,
    vjust=1.5,hjust=0,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx2)+
  labs(
    title="生活過得好不好(N)",x="年度",y="平均分數",caption = "(1分最低，7分最高)")+mytheme->graph$life10n
    
###graph$health_10
data6 %>%
  ggplot(aes(x=birth_p, y=point, group=category, color=category))+
  geom_line(linetype="solid", alpha=0.4,size=1)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=point,
    vjust=1.2,hjust=1,size=5,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx2)+
  scale_color_discrete(
  labels=c("Health","Shealth"))+
  labs(
    title="主樣本和其伴侶的自評健康分數",x="主樣本出生世代",y="平均分數",caption = "(2.5 ~ 4.5區間，1分最低，5分最高)")+
    mytheme+ylim(2.5,4.5)+
    annotate("text",x = 1:7, y=4.5,size=4, label=c("2558","5598","7242","5377","8663","9499","947"),colour="#F8766D",fontface="bold")+
annotate("text",x = 1:7, y=4.4,size=4, label=c("1555","4284","5894","4406","5363","3668","165"),colour="#00BFC4",fontface="bold")+
annotate("text",x=0.5,y=4.45,size=5,label="N",fontface="bold")->graph$health10

### health Shealth n
data6 %>%
  filter(category == "O") %>%
  ggplot(aes(x=birth_p,y=n))+
  geom_bar(stat="identity", fill="#F8766D", width=0.7)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=n,size=5,
    vjust=1.5,hjust=0,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx2)+
  labs(
    title="自評健康分數(N)",x="波次",y="平均分數",caption = "(1分最低，5分最高)")+mytheme->graph$health10n

data6 %>%
  filter(category == "S") %>%
  ggplot(aes(x=birth_p,y=n))+
  geom_bar(stat="identity", fill="#00BFC4", width=0.7)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=n,size=5,
    vjust=1.5,hjust=0,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx2)+
  labs(
    title="伴侶健康分數(N)",x="波次",y="平均分數",caption = "(1分最低，5分最高)")+mytheme->graph$Shealth10n

###graph$work_10
data11 %>%
  ggplot(aes(x=birth_p, y=point, group=category, color=category))+
  geom_line(linetype="solid",alpha=0.4,size=1)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=point,
    size=5,
    vjust=1.6,hjust=1,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx2)+
  scale_color_discrete(
  labels=c("Eco","Work"))+
  labs(title=
    "主樣本的工作、經濟滿意度分數",
      x="主樣本出生世代",y="平均分數",
        caption="(2.5 ~ 3.5區間，1分最低，4分最高)")+
   mytheme+ylim(2.5,3.5)+annotate("text",x = 1:7, y=3.4,size=4, label=c("316","839","1157","829","1794","2899","419"),colour="#F8766D",fontface="bold")+
annotate("text",x = 1:7, y=3.5,size=4, label=c("316","1283","3474","3778","6294","6026","376"),colour="#00BFC4",fontface="bold")+
annotate("text",x=0.5,y=3.45,size=5,label="N",fontface="bold")->graph$work10

### eco work n

data11 %>%
  filter(category == "E") %>%
  ggplot(aes(x=birth_p,y=n))+
  geom_bar(stat="identity", fill="#F8766D", width=0.7)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=n,size=5,
    vjust=1.5,hjust=0,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx2)+
  labs(
    title="經濟滿意度(N)",x="波次",y="平均分數",caption = "(1分最低，4分最高)")+mytheme->graph$eco10n
    
data11 %>%
  filter(category == "W") %>%
  ggplot(aes(x=birth_p,y=n))+
  geom_bar(stat="identity", fill="#00BFC4", width=0.7)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=n,size=5,
    vjust=1.5,hjust=0,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx2)+
  labs(
    title="工作滿意度(N)",x="波次",y="平均分數",caption = "(1分最低，4分最高)")+mytheme->graph$work10n

###graph$family_10

data12 %>%
  ggplot(aes(x=birth_p, y=point, group=category, color=category))+
  geom_line(linetype="solid", size=1,alpha=0.4)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=point,
    vjust=1.6,hjust=0.8,size=5,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx2)+
  scale_color_discrete(
  labels=c("Family","Marry"))+
  labs(
  title=
    "主樣本的家庭、婚姻(同居)滿意度分數",
      x="主樣本出生世代",y="平均分數",
        caption="(2.5 ~ 3.5區間，1分最低，4分最高)")+
  mytheme+ylim(2.5,3.5)+annotate("text",x = 1:7, y=3.45,size=4, label=c("2126","4665","5998","4479","7110","6789","421"),colour="#F8766D",fontface="bold")+
annotate("text",x = 1:7, y=3.5,size=4, label=c("62","269","427","329","645","1026","85"),colour="#00BFC4",fontface="bold")+
annotate("text",x=0.5,y=3.475,size=5,label="N",fontface="bold")->graph$family10

### family marry n

data12 %>%
  filter(category == "F") %>%
  ggplot(aes(x=birth_p,y=n))+
  geom_bar(stat="identity", fill="#F8766D", width=0.7)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=n,size=5,
    vjust=1.5,hjust=0,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx2)+
  labs(
    title="家庭滿意度(N)",x="波次",y="平均分數",caption = "(1分最低，4分最高)")+mytheme->graph$family10n

data12 %>%
  filter(category == "M") %>%
  ggplot(aes(x=birth_p,y=n))+
  geom_bar(stat="identity", fill="#00BFC4", width=0.7)+
  geom_point(size=3,alpha=0.8)+
  geom_text(aes(label=n,size=5,
    vjust=1.5,hjust=0,
    fontface="bold"),
    show.legend = FALSE)+
  scale_x_discrete(labels=labelsx2)+
  labs(
    title="婚姻(同居)滿意度(N)",x="波次",y="平均分數",caption = "(1分最低，4分最高)")+mytheme->graph$marry10n
    
### save

save(graph, file="psfdPlot.Rda")