---
title: "life_cohort"
author: "Wang"
date: "2020/10/28"
output: html_document
---

```{r}
library(rio)
library(plotly)
library(dplyr)
library(tidyr)
library(extrafont)
```
###import wang
```{r}
import("D:/satis/RIRR.sav")->wang
labelsx=c("25-29","30-34","35-39","40-44","45-49","50-54","55-59","60-64","65-69","70-74")
summary(wang$age)
```
###birth_group
```{r}
for(i in 1:nrow(wang)){
  if(wang$age[i] %in% 25:29){
    wang$birth_g[i]<-"1"
  }else if (wang$age[i] %in% 30:34){wang$birth_g[i]<-"2"
  }else if (wang$age[i] %in% 35:39){wang$birth_g[i]<-"3"
  }else if (wang$age[i] %in% 40:44){wang$birth_g[i]<-"4"
  }else if (wang$age[i] %in% 45:49){wang$birth_g[i]<-"5"
  }else if (wang$age[i] %in% 50:54){wang$birth_g[i]<-"6"
  }else if (wang$age[i] %in% 55:59){wang$birth_g[i]<-"7"
  }else if (wang$age[i] %in% 60:64){wang$birth_g[i]<-"8"
  }else if (wang$age[i] %in% 65:69){wang$birth_g[i]<-"9"
  }else if (wang$age[i] %in% 70:74){wang$birth_g[i]<-"10"
  }else{wang$birth_g[i]<-NA
  }
}

```
###birth_period
```{r}
summary(wang$birth_y)
wang %>%
  drop_na(birth_y)->wang
for(i in 1:nrow(wang)){
  if(wang$birth_y[i] %in% 23:38){
    wang$birth_p[i]<-"1949以前"
  }else if (wang$birth_y[i] %in% 39:45){wang$birth_p[i]<-"1950 - 56"
  }else if (wang$birth_y[i] %in% 46:52){wang$birth_p[i]<-"1957 - 63"
  }else if (wang$birth_y[i] %in% 53:59){wang$birth_p[i]<-"1964 - 70"
  }else if (wang$birth_y[i] %in% 60:65){wang$birth_p[i]<-"1971 - 76"
  }else if (wang$birth_y[i] %in% 66:72){wang$birth_p[i]<-"1977 - 83"
  }else if (wang$birth_y[i] %in% 73:80){wang$birth_p[i]<-"1984以後"
  }else{wang$birth_p[i]<-NA
  }
}

table(wang$birth_p, wang$birth_g)
```
###happy df
```{r}
wang %>%
  drop_na(happy) %>%
  group_by(birth_p, birth_g) %>%
  summarise(point=mean(happy),n=n())->happy

happy %>%
  drop_na(birth_g)->happy
as.numeric(happy$birth_g)->happy$birth_g
as.factor(happy$birth_g)->happy$birth_g
as.factor(happy$birth_p)->happy$birth_p
happy$point <- round(happy$point, digits = 2)
levels(happy$birth_p)
```
###life df
```{r}
wang %>%
  drop_na(life) %>%
  group_by(birth_p, birth_g) %>%
  summarise(point=mean(life),n=n())->life

life %>%
  drop_na(birth_g)->life
as.numeric(life$birth_g)->life$birth_g
as.factor(life$birth_g)->life$birth_g
as.factor(life$birth_p)->life$birth_p
life$point <- round(life$point, digits = 2)
levels(life$birth_p)
```
### health df
```{r}
wang %>%
  drop_na(health) %>%
  group_by(birth_p, birth_g) %>%
  summarise(point=mean(health),n=n())->health

health %>%
  drop_na(birth_g)->health
as.numeric(health$birth_g)->health$birth_g
as.factor(health$birth_g)->health$birth_g
as.factor(health$birth_p)->health$birth_p
health$point <- round(health$point, digits = 2)
levels(health$birth_p)
```
### Shealth df
```{r}
wang %>%
  drop_na(Shealth) %>%
  group_by(birth_p, birth_g) %>%
  summarise(point=mean(Shealth),n=n())->Shealth

Shealth %>%
  drop_na(birth_g)->Shealth
as.numeric(Shealth$birth_g)->Shealth$birth_g
as.factor(Shealth$birth_g)->Shealth$birth_g
as.factor(Shealth$birth_p)->Shealth$birth_p
Shealth$point <- round(Shealth$point, digits = 2)
levels(Shealth$birth_p)
```
### eco_satis df
```{r}
wang %>%
  drop_na(eco_satis) %>%
  group_by(birth_p, birth_g) %>%
  summarise(point=mean(eco_satis),n=n())->eco_satis

eco_satis %>%
  drop_na(birth_g)->eco_satis
as.numeric(eco_satis$birth_g)->eco_satis$birth_g
as.factor(eco_satis$birth_g)->eco_satis$birth_g
as.factor(eco_satis$birth_p)->eco_satis$birth_p
eco_satis$point <- round(eco_satis$point, digits = 2)
levels(eco_satis$birth_p)
```
### work_satis df
```{r}
wang %>%
  drop_na(work_satis) %>%
  group_by(birth_p, birth_g) %>%
  summarise(point=mean(work_satis),n=n())->work_satis

work_satis %>%
  drop_na(birth_g)->work_satis
as.numeric(work_satis$birth_g)->work_satis$birth_g
as.factor(work_satis$birth_g)->work_satis$birth_g
as.factor(work_satis$birth_p)->work_satis$birth_p
work_satis$point <- round(work_satis$point, digits = 2)
levels(work_satis$birth_p)
```
### family_satis df
```{r}
wang %>%
  drop_na(family_satis) %>%
  group_by(birth_p, birth_g) %>%
  summarise(point=mean(family_satis),n=n())->family_satis

family_satis %>%
  drop_na(birth_g)->family_satis
as.numeric(family_satis$birth_g)->family_satis$birth_g
as.factor(family_satis$birth_g)->family_satis$birth_g
as.factor(family_satis$birth_p)->family_satis$birth_p
family_satis$point <- round(family_satis$point, digits = 2)
levels(family_satis$birth_p)
```
### marry_satis df
```{r}
wang %>%
  drop_na(marry_satis) %>%
  group_by(birth_p, birth_g) %>%
  summarise(point=mean(marry_satis),n=n())->marry_satis

marry_satis %>%
  drop_na(birth_g)->marry_satis
as.numeric(marry_satis$birth_g)->marry_satis$birth_g
as.factor(marry_satis$birth_g)->marry_satis$birth_g
as.factor(marry_satis$birth_p)->marry_satis$birth_p
marry_satis$point <- round(marry_satis$point, digits = 2)
levels(marry_satis$birth_p)
```
###graph4$happy
```{r}
graph4<-list()
ggplotly(
  ggplot(happy, aes(x=birth_g, y=point, group=birth_p, color=birth_p, text = paste(
  "Period:", birth_p,
  "<br>N:", n, 
  "<br>Point:", point)))+
  geom_line(linetype="solid",alpha=0.4, size=1)+
  geom_point(size=2,alpha=0.7)+
  scale_x_discrete(labels=labelsx)+
  labs(
    title="主樣本的生活快樂感(出生世代)",
    x="主樣本年齡",y="平均分數(1 ~ 7分)")+
  ylim(4,5.5), tooltip = "text"
  ) %>%
    layout(legend = list(
        orientation = "h"
        )
      )->graph4$happy
```
###graph4$life
```{r}
ggplotly(
  ggplot(life, aes(x=birth_g, y=point, group=birth_p, color=birth_p, text = paste(
  "Period:", birth_p,
  "<br>N:", n, 
  "<br>Point:", point)))+
  geom_line(linetype="solid",alpha=0.4, size=1)+
  geom_point(size=2,alpha=0.7)+
  scale_x_discrete(labels=labelsx)+
  labs(
    title="主樣本的生活過得好不好(出生世代)",
    x="主樣本年齡",y="平均分數(1 ~ 7分)")+
  ylim(4,5.5), tooltip = "text"
  ) %>%
    layout(legend = list(
        orientation = "h"
        )
      )->graph4$life
```
### graph4$health
```{r}
ggplotly(
  ggplot(health, aes(x=birth_g, y=point, group=birth_p, color=birth_p, text = paste(
  "Period:", birth_p,
  "<br>N:", n, 
  "<br>Point:", point)))+
  geom_line(linetype="solid",alpha=0.4, size=1)+
  geom_point(size=2,alpha=0.7)+
  scale_x_discrete(labels=labelsx)+
  labs(
    title="主樣本的健康狀態(出生世代)",
    x="主樣本年齡",y="平均分數(1 ~ 5分)")+
  ylim(2.5,4.5), tooltip = "text"
  ) %>%
    layout(legend = list(
        orientation = "h"
        )
      )->graph4$health
```
### graph4$Shealth
```{r}
ggplotly(
  ggplot(Shealth, aes(x=birth_g, y=point, group=birth_p, color=birth_p, text = paste(
  "Period:", birth_p,
  "<br>N:", n, 
  "<br>Point:", point)))+
  geom_line(linetype="solid",alpha=0.4, size=1)+
  geom_point(size=2,alpha=0.7)+
  scale_x_discrete(labels=labelsx)+
  labs(
    title="主樣本伴侶的健康狀態(出生世代)",
    x="主樣本年齡",y="平均分數(1 ~ 5分)")+
  ylim(2.5,4.5), tooltip = "text"
  ) %>%
    layout(legend = list(
        orientation = "h"
        )
      )->graph4$Shealth
```
### graph4$eco_satis
```{r}
ggplotly(
  ggplot(eco_satis, aes(x=birth_g, y=point, group=birth_p, color=birth_p, text = paste(
  "Period:", birth_p,
  "<br>N:", n, 
  "<br>Point:", point)))+
  geom_line(linetype="solid",alpha=0.4, size=1)+
  geom_point(size=2,alpha=0.7)+
  scale_x_discrete(labels=labelsx)+
  labs(
    title="主樣本經濟滿意度(出生世代)",
    x="主樣本年齡",y="平均分數(1 ~ 4分)")+
  ylim(2.5,3.5), tooltip = "text"
  ) %>%
    layout(legend = list(
        orientation = "h"
        )
      )->graph4$eco_satis
```
### graph4$work_satis
```{r}
ggplotly(
  ggplot(work_satis, aes(x=birth_g, y=point, group=birth_p, color=birth_p, text = paste(
  "Period:", birth_p,
  "<br>N:", n, 
  "<br>Point:", point)))+
  geom_line(linetype="solid",alpha=0.4, size=1)+
  geom_point(size=2,alpha=0.7)+
  scale_x_discrete(labels=labelsx)+
  labs(
    title="主樣本工作滿意度(出生世代)",
    x="主樣本年齡",y="平均分數(1 ~ 4分)")+
  ylim(2.5,3.5), tooltip = "text"
  ) %>%
    layout(legend = list(
        orientation = "h"
        )
      )->graph4$work_satis
```
### graph4$family_satis
```{r}
ggplotly(
  ggplot(family_satis, aes(x=birth_g, y=point, group=birth_p, color=birth_p, text = paste(
  "Period:", birth_p,
  "<br>N:", n, 
  "<br>Point:", point)))+
  geom_line(linetype="solid",alpha=0.4, size=1)+
  geom_point(size=2,alpha=0.7)+
  scale_x_discrete(labels=labelsx)+
  labs(
    title="主樣本家庭滿意度(出生世代)",
    x="主樣本年齡",y="平均分數(1 ~ 4分)")+
  ylim(2.5,3.5), tooltip = "text"
  ) %>%
    layout(legend = list(
        orientation = "h"
        )
      )->graph4$family_satis
```
### graph4$marry_satis
```{r}
ggplotly(
  ggplot(marry_satis, aes(x=birth_g, y=point, group=birth_p, color=birth_p, text = paste(
  "Period:", birth_p,
  "<br>N:", n, 
  "<br>Point:", point)))+
  geom_line(linetype="solid",alpha=0.4, size=1)+
  geom_point(size=2,alpha=0.7)+
  scale_x_discrete(labels=labelsx)+
  labs(
    title="主樣本婚姻(同居)滿意度(出生世代)",
    x="主樣本年齡",y="平均分數(1 ~ 4分)")+
  ylim(2.5,3.5), tooltip = "text"
  ) %>%
    layout(legend = list(
        orientation = "h"
        )
      )->graph4$marry_satis
```
### save data and graph
```{r}
save(
  happy, life, health, Shealth, eco_satis, work_satis, family_satis, marry_satis, labelsx,
  file="psfdcohort.Rda")
save(graph4, file="psfdplot_cohort.Rda")
```

